# Generated by Django 3.0.8 on 2020-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('IdBeer', models.IntegerField(primary_key=True, serialize=False)),
                ('Percentage', models.FloatField()),
                ('Brand', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Idkind', models.IntegerField()),
                ('Detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KinDrink',
            fields=[
                ('IdKind', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdBeer', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('DateLog', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUser', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Enable', models.BooleanField(default=True)),
            ],
        ),
    ]
