# Generated by Django 3.0.8 on 2020-07-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('IdBeers', models.IntegerField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdBeer', models.IntegerField()),
                ('IdUser', models.IntegerField()),
                ('dateLog', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpTake',
            fields=[
                ('IdBeers', models.IntegerField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('detail', models.CharField(max_length=300)),
                ('cantida', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='KinDrink',
            new_name='Kind',
        ),
        migrations.DeleteModel(
            name='Beers',
        ),
        migrations.DeleteModel(
            name='Selections',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='Name',
            new_name='name',
        ),
    ]
